config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#map'
  get 'map', to: 'projects#map', as: :map
  get 'map_results', to: 'projects#map_results', as: :map_results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
require 'csv'

class Project < ApplicationRecord
  geocoded_by :adresse_complete
  validates :adresse_complete, presence: true
  validates :rate_obtained, presence: true

  after_validation :geocode, if: :will_save_change_to_adresse_complete?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
require 'action_view'
include ActionView::Helpers::NumberHelper

class ProjectsController < ApplicationController
  before_action :set_projects

  def map
  end

  def map_results
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @projects.geocoded.map do |project|
      {
        lat: project.latitude,
        lng: project.longitude,
        address: project.adresse_with_city,
        rate: project.rate_obtained,
        duration: project.duration,
        loan_amount: number_to_human(project.loan_amount, :format => '%n%u', :units => { :thousand => 'K' }),
        nb_mortgagors: project.nb_mortgagors,
        total_income: number_to_human(project.total_income, :format => '%n%u', :units => { :thousand => 'K' }),
        age: project.age_moyen
      }
    end

    render json: @markers
  end

  private

  def set_projects
    if params[:duration].present?
      @projects = Project.all.where(duration: params[:duration])
    else
      @projects = Project.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CartoPretto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="https://www.pretto.fr/favicon-32x32-7d8534c14e97608fb4e958cbc9df2fc1.png" type="image/png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :address %>
    <%= f.input :zipcode %>
    <%= f.input :rate %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/map.html.erb
<div id='vue-app'></div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @project.address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @project.zipcode %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @project.rate %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>